Add support for DFPlayer modules using a MH2024K-16SS chip
Makuna/DFMiniMp3 pull request #77
Opened 2021-08-23 18:56 UTC by MaximeCheramy

This PR adds support of DFPlayer modules that use a MH2024K-16SS chip. The main difference is that the packet sent to the module **must not** contain the checksum. The command code emitted when a song finishes is also different.

A new flag can be passed to the constructor `sendChecksum` which defaults to `true` and must be set to `false` for the MH2024K-16SS.

This MR also refactors the packet: instead of an enum, it's now a struct. However, that change wasn't mandatory for the support of this new chip.

The original idea to remove the checksum comes from this branch: https://github.com/bkk87/DFMiniMp3/blob/1.0.7-noChecksums-fixcase/src/DFMiniMp3.h (cc @bkk87)

I don't have another DFPlayer module with another chip to test.

2021-08-23 20:21 UTC, Makuna commented
I have no idea why, but I could not start a code review this request.  I embedded comments and you will need to apply them before it will get merged in.

Don't get discouraged from my comments, most are minor, and the biggest I would have expected few people to do the way I would want and will more than likely require you to talk to me more about the template details.

2021-08-23 20:30 UTC, MaximeCheramy commented
@Makuna which formatter do you use? Do you have a configuration file? If not, I'll try to configure my formatter using your comments.

2021-08-23 20:40 UTC, Makuna commented
> @Makuna which formatter do you use? Do you have a configuration file? If not, I'll try to configure my formatter using your comments.

I use VS and I believe its the default formatter (other than setting tabs to 4 spaces).

2021-08-23 20:42 UTC, MaximeCheramy commented
> I use VS and I believe its the default formatter (other than setting tabs to 4 spaces).

I used VSCode with the default formatter (I believe)... I try to make it compatible with your current format.

2021-08-23 20:45 UTC, MaximeCheramy commented
I'll address your comments tomorrow.

2021-08-23 23:00 UTC, MaximeCheramy commented
To avoid implementing something that doesn't fit what you have in mind, can you explain more in details what you meant by:
> This is where templates come in, add another template argument and provide two template instances where one has a true const static member and one has a false const static member.

What would expose that class? If it's just a boolean with true/false, I suppose this saves a byte in memory but keeps the branch. So instead I could expose 2 methods: 1 to generate the packet (as uint8_t*) and another to return the packet size? I suppose the compiler would inline, otherwise this would replace a branch by function calls...

2021-08-24 18:42 UTC, Makuna commented
> To avoid implementing something that doesn't fit what you have in mind, can you explain more in details what you meant by:
> 
> > This is where templates come in, add another template argument and provide two template instances where one has a true const static member and one has a false const static member.
> 
> What would expose that class? If it's just a boolean with true/false, I suppose this saves a byte in memory but keeps the branch. So instead I could expose 2 methods: 1 to generate the packet (as uint8_t*) and another to return the packet size? I suppose the compiler would inline, otherwise this would replace a branch by function calls...

OK, put on your deep diving gear, as we are jumping into the deep end...

I am going to reference another project of mine that demonstrates the concept for const variables:
This lines defines a class that contains a specific set of const, there are others following it that provide other values...
https://github.com/Makuna/NeoPixelBus/blob/0913134003687013d24807fe8d3027ba9cdc2d9f/src/internal/NeoEsp32I2sMethod.h#L40
And one of these is supplied to the template class defined on this line...
https://github.com/Makuna/NeoPixelBus/blob/0913134003687013d24807fe8d3027ba9cdc2d9f/src/internal/NeoEsp32I2sMethod.h#L145
And you can see the const used on this line within that template class
https://github.com/Makuna/NeoPixelBus/blob/0913134003687013d24807fe8d3027ba9cdc2d9f/src/internal/NeoEsp32I2sMethod.h#L189
and you can see it being used on the template class to define a new type (this part you don't need to do; just showing how its used)
https://github.com/Makuna/NeoPixelBus/blob/0913134003687013d24807fe8d3027ba9cdc2d9f/src/internal/NeoEsp32I2sMethod.h#L284

You can do the same with methods, but its still best to leave them as `inline constexpr static` to allow the compiler better optimizations; which means passing needed data to them.
https://github.com/Makuna/NeoPixelBus/blob/0913134003687013d24807fe8d3027ba9cdc2d9f/src/internal/NeoEsp32RmtMethod.h#L89

2021-08-24 20:42 UTC, MaximeCheramy commented
Yesterday I started doing exactly what you did in NeoPixelBus, however this was not removing the branch in the code and I was unhappy about that. However, and this is what I didn't understand, the compiler is able to remove the unused block (to remove the branch).

Now, the most complex question: how would you call these classes/template? T_SEND_FEEDBACK (to contain only this boolean)? T_SETTINGS (to contain other settings in the future)?

2021-08-24 22:18 UTC, Makuna commented
I think the best approach is to think of this as the chipset/variant nuances.  So maybe...
T_CHIP_VARIANT
and the instances...
Mp3ChipMh2024h16ss
Mp3ChipOriginal

2021-08-28 20:23 UTC, MaximeCheramy commented on src/DFMiniMp3.h
> +    union DfMp3_Packet {
I've removed the if and moved the generation of the packet to the Mp3Chip classes: b62bb5c

2021-08-29 16:29 UTC, Makuna requested changes
one last minor thing

2021-08-29 16:29 UTC, Makuna commented on src/DFMiniMp3.h
> +bool validateChecksum(DfMp3_Packet_WithCheckSum& in)
in should be const

2021-08-29 18:26 UTC, MaximeCheramy commented on src/DFMiniMp3.h
> +bool validateChecksum(DfMp3_Packet_WithCheckSum& in)
done here: 5a2616e

2021-08-30 15:00 UTC, Makuna approved these changes

2021-08-30 15:00 UTC, merged